### ISSUE TITLE
Inactiveなタブの画面を取得できるか検証する

### ISSUE THREAD

**Issue by aoirint** [miniature-octo-guide/spatial-volume-controller#13]
https://github.com/miniature-octo-guide/spatial-volume-controller/issues/8
これの`video:true`版。

```typescript
chrome.tabCapture.capture({ audio: false, video: true }, (stream: MediaStream) => {
  // ?
})
```

**Comment by aoirint** [comment]
https://developer.chrome.com/docs/extensions/reference/tabCapture/

**Comment by aoirint** [comment]
画面上にちっちゃく表示する、みたいなことができたらいいな

**Comment by aoirint** [comment]
今は拡張機能のアイコンをクリックしたら新しいタブが開く処理をしている。
https://github.com/miniature-octo-guide/spatial-volume-controller/blob/5de88f20e861305dcb201db8056c29341f22ae3f/app/scripts/background.ts#L9

検証のときは、アイコンをクリックしたときにグローバル変数として持ってるキュー（リスト）にMediaStream的な何かを追加しておいて、あとでindex.htmlかどこかでまとめて表示・操作する処理をする、みたいな感じになると思う（テスト環境があればもっとマシなやり方だったかもしれん..）。

拡張機能アイコンをクリックしたときにポップアップでHTMLを表示させることもできる（過去のコミットを参照してくれ、popup.htmlが存在していたころのやつ。それほど差分はない）。

いま検証してる方式で作る場合（たぶんこれでいくけど）、ポップアップを復活させて、ポップアップ内の「現在のタブをキューに追加」ボタンを押す、みたいな作りになりそうな気がする。これだとindex.htmlへの導線が微妙になるんだけど..。なんかいい方法ないかな。

**Comment by manabe5260** [comment]
chrome.tabCapture.capture追加するとでる
Error handling response: TypeError: Failed to execute 'createMediaStreamSource' on 'AudioContext': parameter 1 is not of type 'MediaStream'.
Unchecked runtime.lastError: Extension has not been invoked for the current page (see activeTab permission). Chrome pages cannot be captured.

**Comment by aoirint** [comment]
> chrome.tabCapture.capture追加するとでる
> Error handling response: TypeError: Failed to execute 'createMediaStreamSource' on 'AudioContext': parameter 1 is not of type 'MediaStream'.
> Unchecked runtime.lastError: Extension has not been invoked for the current page (see activeTab permission). Chrome pages cannot be captured.

https://github.com/miniature-octo-guide/spatial-volume-controller/issues/8#issuecomment-786999315
https://github.com/miniature-octo-guide/spatial-volume-controller/issues/8#issuecomment-786999582
に回答書いた

**Comment by aoirint** [comment]
こっちにも関係してくるんだけど

**Comment by aoirint** [comment]
https://github.com/GoogleChrome/chrome-extensions-samples/blob/main/apps/samples/desktop-capture/app.js#L68

```typescript
stream: MediaStream
document.querySelector('video').src = URL.createObjectURL(stream);
```

ワンチャンこういうコードでいけるかも？
videoはHTMLのvideoタグ

**Comment by aoirint** [comment]
https://developer.mozilla.org/ja/docs/Web/API/Document/querySelector
https://developer.mozilla.org/ja/docs/Web/API/URL/createObjectURL

**Comment by aoirint** [comment]
https://developer.chrome.com/docs/extensions/mv2/messaging/

`chrome.runtime.sendMessage`と`chrome.runtime.onMessage.addListener`がbackgroundとindexの通信に使えそう
ワンチャンlocalStorageになるかもしれないけど..

**Comment by aoirint** [comment]
https://r17n.page/2019/10/27/chrome-extension-message-from-background-to-content/
ここにはbackground to indexできるって書いてある気がする

**Comment by aoirint** [comment]
index側からbackground側へ、いま保持しているStreamのリストを返してくれ、って要求を送るスクリプトになるかもしれん

**Comment by aoirint** [comment]
それでJSオブジェクトの受け渡しができるのかよくわからないけど..

**Comment by aoirint** [comment]
https://html5experts.jp/mganeko/19814/
https://qiita.com/yusuke84/items/43a20e3b6c78ae9a8f6c

**Comment by aoirint** [comment]
Closed by #16.
Thanks, @RyotaYamamoto990319 !
