### ISSUE TITLE
UIの改善

### ISSUE THREAD

**Issue by yamamotty** [miniature-octo-guide/spatial-volume-controller#25]
・やまねっこが作ったUIの統合
・listenerアイコンを離したときに透過させる

（できれば）
・speakerアイコンの自動配置
・listenerアイコンの画像をgoogleアカウントの画像にする

**Comment by aoirint** [comment]
Chromeにログインしてるユーザのアイコンって取れるのか??
localStorageとかにアップロードさせるのでもいい気がする
