### ISSUE TITLE
ListenerIconがSpeakerIconに隠れてしまうことがある

### ISSUE THREAD

**Issue by aoirint** [miniature-octo-guide/spatial-volume-controller#27]
ListenerIconのz-indexをいじって常に前面表示されるようにしたい

**Comment by yamamotty** [comment]
これなんだけど，#25にある通り，listenerIconを全面表示で透過させた方がいいんじゃないかな，と思った

**Comment by aoirint** [comment]
それっぽい透過は
opacity: 0.5
とか
hover擬似クラス
とか使えばできる気がする
